import hashlib
import logging
from abc import abstractmethod

class BaseGenerator(object):
	ATTR_MAP = {}

	LINUX_OS = ['pfsense', 'ubuntu', 'centos']
	WINDOWS_OS = ['windows']
	CAN_CUSTOMIZE_OS = ['ubuntu', 'centos', 'windows']

	CUSTOM_POST_PROVISION_HOSTS = ['pfsense']

	AUTOGENERATED_HEADER = [
		"#######################################",
		"# WARNING: THIS FILE IS AUTOGENERATED #",
		"# DO NOT EDIT MANUALLY                #",
		"#######################################",
		"",
	]

	def __init__(self, config, deploy):
		self.config = config
		self.deploy = deploy

		self.logger = logging.getLogger(__name__)

		self.templates = {}
		for tpl in config['templates']:
			self.templates[tpl['id']] = tpl

	def validate(self):
		return True

	@abstractmethod
	def generate(self):
		pass

	def _id(self, name):
		return hashlib.md5(name.encode('utf-8')).hexdigest()
