import yaml
from genesis.deployment import BaseDeployer

class pfsenseProvision(BaseDeployer):
	PFSENSE_PROVISION_ROLE = 'pf_provision'
	PFSENSE_PROVISION_FILE = '05-deploy-postprovision.yml'
	PFSENSE_ANSIBLE_PROVISION = 'ansible-pfsense-provision'

	def generate(self, data):
		# Generate the config
		with open("{}/{}".format(data['step_dir'], self.PFSENSE_PROVISION_FILE), 'w') as fp:
			fp.write(self._generate_yml(data))

		# Copy over the roles
		self._copy("{}/{}".format(self.args.data, self.PFSENSE_ANSIBLE_PROVISION), "{}/roles".format(data['step_dir']))

	def execute(self, data):
		return [
			['ansible-playbook', self.PFSENSE_PROVISION_FILE]
		]

	def _generate_yml(self, data):
		out = []

		for host in data['post_provision_pfsense_hosts']:
			# I'm being lazy for getting the platform config, sorry.
			platform = self.config['platforms']['vmware']

			# I'm also being terrible with the gw/wan/lan/opt
			gw = host['networks'][0]['gateway']
			wan = host['networks'][0]['ip']
			lan = host['networks'][1]['ip']
			opt = host['networks'][2]['ip']

			out_host = {
				'hosts': 'localhost',
				'tasks': [
					{
						'include_role': {
							'name': self.PFSENSE_PROVISION_ROLE
						},
						'vars': {
							'vcenter_host': platform['host'],
							'vcenter_user': platform['user'],
							'vcenter_pass': platform['pass'],
							'vcenter_dc': host['datacenter'],
							'vm_folder': "/{datacenter}/vm/{folder}".format(**host),
							'vm_id': host['name'],
							'vm_user': self.deploy.templates[host['template']]['username'],
							'vm_pass': self.deploy.templates[host['template']]['password'],
							'cfg_gw': gw,
							'cfg_wan': wan,
							'cfg_lan': lan,
							'cfg_opt': opt
						}
					}
				],
			}

			out.append(out_host)

		return '\n'.join(self.AUTOGENERATED_HEADER) + yaml.dump(out)